// <auto-generated />
using System;
using Infrastruktura.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WebApi.Migrations
{
    [DbContext(typeof(ZamestnanciContext))]
    [Migration("20221012191838_CreateDatabaseNew")]
    partial class CreateDatabaseNew
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Latin1_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Infrastruktura.Models.Pozicie", b =>
                {
                    b.Property<int>("PoziciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PoziciaID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazovPozicie")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("PoziciaId");

                    b.ToTable("Pozicie");
                });

            modelBuilder.Entity("Infrastruktura.Models.PredoslePozicie", b =>
                {
                    b.Property<int>("IDPredoslej")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumNastupu")
                        .HasColumnType("date")
                        .HasColumnName("datumNastupu");

                    b.Property<DateTime>("DatumUkoncenia")
                        .HasColumnType("date")
                        .HasColumnName("datumUkoncenia");

                    b.Property<int>("PoziciaId")
                        .HasColumnType("int")
                        .HasColumnName("poziciaId");

                    b.Property<int>("ZamestnanecId")
                        .HasColumnType("int")
                        .HasColumnName("ZamestnanecId");

                    b.HasKey("IDPredoslej");

                    b.HasIndex("PoziciaId");

                    b.ToTable("PredoslePozicie");
                });

            modelBuilder.Entity("Infrastruktura.Models.Zamestnanci", b =>
                {
                    b.Property<int>("ZamestnanecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ZamestnanecID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("adresa");

                    b.Property<bool>("Archivovany")
                        .HasColumnType("bit")
                        .HasColumnName("archivovany");

                    b.Property<DateTime>("DatumNarodenia")
                        .HasColumnType("date");

                    b.Property<DateTime>("DatumNastupu")
                        .HasColumnType("date");

                    b.Property<string>("Meno")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PoziciaId")
                        .HasColumnType("int")
                        .HasColumnName("PoziciaId");

                    b.Property<string>("Priezvisko")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ZamestnanecId");

                    b.HasIndex("PoziciaId");

                    b.ToTable("Zamestnanci");
                });

            modelBuilder.Entity("Infrastruktura.Models.PredoslePozicie", b =>
                {
                    b.HasOne("Infrastruktura.Models.Pozicie", "Pozicie")
                        .WithMany()
                        .HasForeignKey("PoziciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pozicie");
                });

            modelBuilder.Entity("Infrastruktura.Models.Zamestnanci", b =>
                {
                    b.HasOne("Infrastruktura.Models.Pozicie", "Pozicie")
                        .WithMany()
                        .HasForeignKey("PoziciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pozicie");
                });
#pragma warning restore 612, 618
        }
    }
}
